name: patidar_melap_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # internationalization
  timeago: ^3.6.0
  easy_localization: ^3.0.3

  # environment management
  envied: ^0.5.2

  # secure local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Class comparison and form validation
  equatable: ^2.0.5
  flutter_form_bloc:
    git:
      url: https://github.com/Cavin6080/form_bloc.git
      path: packages/flutter_form_bloc
      branch: development

  # Utils
  logger: ^2.0.2+1
  pretty_dio_logger: ^1.3.1
  path_provider: ^2.1.1

  # State management and dependency injection
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  hydrated_bloc: ^9.1.2
  get_it: ^7.6.4

  #Routing
  auto_route: ^7.8.4

  # api client
  dio: ^5.3.3
  dio_cache_interceptor_hive_store: ^3.2.1

  # functional programming
  fpdart: ^1.1.0
  data_connection_checker_nulls: ^0.0.2

  # Image picker
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.0
  image_cropper: ^5.0.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  # Usage: flutter packages pub run dependency_validator
  dependency_validator: ^3.2.3

  # For generating code
  build_runner: ^2.4.6

  # For generating assets code
  flutter_gen: ^5.3.2
  flutter_gen_runner: ^5.3.2

  # For generating routes
  auto_route_generator: ^7.3.2

  # For generating hive model adaptors
  hive_generator: ^2.0.1
  very_good_analysis: ^5.1.0

  # For generating env files
  envied_generator: ^0.5.2

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/l10n/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: muktaVaani
      fonts:
        - asset: assets/fonts/MuktaVaani-Bold.ttf
          weight: 700
        - asset: assets/fonts/MuktaVaani-Medium.ttf
          weight: 600
        - asset: assets/fonts/MuktaVaani-regular.ttf
          weight: 500